services:
  - type: web
    name: de-m3u8-a-mp4
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000
    plan: free